apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  selector:
    matchLabels:
      app: webserver
  replicas: 1
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - image: quay.io/redhatworkshops/bgd:latest
        name: webapp 
        env:
        - name: COLOR
          value: "blue"
        ports:
        - containerPort: 8080
