apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: quay.io/redhatworkshops/bgd:latest
#      - image: registry.redhat.io/rhel8/httpd-24
        name: webapp 
        env:
        - name: COLOR
          value: "blue"
        ports:
        - containerPort: 8080
